# Generated by Django 2.0.2 on 2019-05-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190503_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='maintainlog',
            name='host',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='MaintainLog',
        ),
    ]
